name: Update Image

on:
  push:
    branches:
      - main  # 僅在 main 分支觸發
  workflow_dispatch:  # 手動觸發
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build server images
      run: |
        docker build --pull --no-cache -f dockerfile.django-eadai -t tsukisama9292/server:django-eadai-rolling .

    - name: Push the Docker image to Docker Hub
      run: |
        docker push tsukisama9292/server:django-eadai-rolling